// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/spc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SPCClient is the client API for SPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SPCClient interface {
	GetHoliday(ctx context.Context, in *GetHolidayRequest, opts ...grpc.CallOption) (*GetHolidayResponse, error)
	AddHoliday(ctx context.Context, in *AddHolidayRequest, opts ...grpc.CallOption) (*AddHolidayResponse, error)
	EditHoliday(ctx context.Context, in *EditHolidayRequest, opts ...grpc.CallOption) (*EditHolidayResponse, error)
	DeleteHoliday(ctx context.Context, in *DeleteHolidayRequest, opts ...grpc.CallOption) (*DeleteHolidayResponse, error)
}

type sPCClient struct {
	cc grpc.ClientConnInterface
}

func NewSPCClient(cc grpc.ClientConnInterface) SPCClient {
	return &sPCClient{cc}
}

func (c *sPCClient) GetHoliday(ctx context.Context, in *GetHolidayRequest, opts ...grpc.CallOption) (*GetHolidayResponse, error) {
	out := new(GetHolidayResponse)
	err := c.cc.Invoke(ctx, "/main.SPC/GetHoliday", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sPCClient) AddHoliday(ctx context.Context, in *AddHolidayRequest, opts ...grpc.CallOption) (*AddHolidayResponse, error) {
	out := new(AddHolidayResponse)
	err := c.cc.Invoke(ctx, "/main.SPC/AddHoliday", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sPCClient) EditHoliday(ctx context.Context, in *EditHolidayRequest, opts ...grpc.CallOption) (*EditHolidayResponse, error) {
	out := new(EditHolidayResponse)
	err := c.cc.Invoke(ctx, "/main.SPC/EditHoliday", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sPCClient) DeleteHoliday(ctx context.Context, in *DeleteHolidayRequest, opts ...grpc.CallOption) (*DeleteHolidayResponse, error) {
	out := new(DeleteHolidayResponse)
	err := c.cc.Invoke(ctx, "/main.SPC/DeleteHoliday", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SPCServer is the server API for SPC service.
// All implementations must embed UnimplementedSPCServer
// for forward compatibility
type SPCServer interface {
	GetHoliday(context.Context, *GetHolidayRequest) (*GetHolidayResponse, error)
	AddHoliday(context.Context, *AddHolidayRequest) (*AddHolidayResponse, error)
	EditHoliday(context.Context, *EditHolidayRequest) (*EditHolidayResponse, error)
	DeleteHoliday(context.Context, *DeleteHolidayRequest) (*DeleteHolidayResponse, error)
	mustEmbedUnimplementedSPCServer()
}

// UnimplementedSPCServer must be embedded to have forward compatible implementations.
type UnimplementedSPCServer struct {
}

func (UnimplementedSPCServer) GetHoliday(context.Context, *GetHolidayRequest) (*GetHolidayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHoliday not implemented")
}
func (UnimplementedSPCServer) AddHoliday(context.Context, *AddHolidayRequest) (*AddHolidayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHoliday not implemented")
}
func (UnimplementedSPCServer) EditHoliday(context.Context, *EditHolidayRequest) (*EditHolidayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditHoliday not implemented")
}
func (UnimplementedSPCServer) DeleteHoliday(context.Context, *DeleteHolidayRequest) (*DeleteHolidayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHoliday not implemented")
}
func (UnimplementedSPCServer) mustEmbedUnimplementedSPCServer() {}

// UnsafeSPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SPCServer will
// result in compilation errors.
type UnsafeSPCServer interface {
	mustEmbedUnimplementedSPCServer()
}

func RegisterSPCServer(s grpc.ServiceRegistrar, srv SPCServer) {
	s.RegisterService(&SPC_ServiceDesc, srv)
}

func _SPC_GetHoliday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHolidayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SPCServer).GetHoliday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.SPC/GetHoliday",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SPCServer).GetHoliday(ctx, req.(*GetHolidayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SPC_AddHoliday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHolidayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SPCServer).AddHoliday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.SPC/AddHoliday",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SPCServer).AddHoliday(ctx, req.(*AddHolidayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SPC_EditHoliday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditHolidayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SPCServer).EditHoliday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.SPC/EditHoliday",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SPCServer).EditHoliday(ctx, req.(*EditHolidayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SPC_DeleteHoliday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHolidayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SPCServer).DeleteHoliday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.SPC/DeleteHoliday",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SPCServer).DeleteHoliday(ctx, req.(*DeleteHolidayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SPC_ServiceDesc is the grpc.ServiceDesc for SPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.SPC",
	HandlerType: (*SPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHoliday",
			Handler:    _SPC_GetHoliday_Handler,
		},
		{
			MethodName: "AddHoliday",
			Handler:    _SPC_AddHoliday_Handler,
		},
		{
			MethodName: "EditHoliday",
			Handler:    _SPC_EditHoliday_Handler,
		},
		{
			MethodName: "DeleteHoliday",
			Handler:    _SPC_DeleteHoliday_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/spc.proto",
}
