// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: spc/spc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HolidayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *HolidayRequest) Reset() {
	*x = HolidayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spc_spc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HolidayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolidayRequest) ProtoMessage() {}

func (x *HolidayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spc_spc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolidayRequest.ProtoReflect.Descriptor instead.
func (*HolidayRequest) Descriptor() ([]byte, []int) {
	return file_spc_spc_proto_rawDescGZIP(), []int{0}
}

func (x *HolidayRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HolidayRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HolidayRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type HolidayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsHoliday   bool   `protobuf:"varint,1,opt,name=is_holiday,json=isHoliday,proto3" json:"is_holiday,omitempty"`
	HolidayId   int32  `protobuf:"varint,2,opt,name=holiday_id,json=holidayId,proto3" json:"holiday_id,omitempty"`
	HolidayName string `protobuf:"bytes,3,opt,name=holiday_name,json=holidayName,proto3" json:"holiday_name,omitempty"`
	HolidayData string `protobuf:"bytes,4,opt,name=holiday_data,json=holidayData,proto3" json:"holiday_data,omitempty"`
}

func (x *HolidayResponse) Reset() {
	*x = HolidayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spc_spc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HolidayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolidayResponse) ProtoMessage() {}

func (x *HolidayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spc_spc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolidayResponse.ProtoReflect.Descriptor instead.
func (*HolidayResponse) Descriptor() ([]byte, []int) {
	return file_spc_spc_proto_rawDescGZIP(), []int{1}
}

func (x *HolidayResponse) GetIsHoliday() bool {
	if x != nil {
		return x.IsHoliday
	}
	return false
}

func (x *HolidayResponse) GetHolidayId() int32 {
	if x != nil {
		return x.HolidayId
	}
	return 0
}

func (x *HolidayResponse) GetHolidayName() string {
	if x != nil {
		return x.HolidayName
	}
	return ""
}

func (x *HolidayResponse) GetHolidayData() string {
	if x != nil {
		return x.HolidayData
	}
	return ""
}

var File_spc_spc_proto protoreflect.FileDescriptor

var file_spc_spc_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x70, 0x63, 0x2f, 0x73, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x48, 0x0a, 0x0e, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x95, 0x01, 0x0a, 0x0f, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x48, 0x6f, 0x6c, 0x69, 0x64,
	0x61, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x49,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x6f, 0x6c, 0x69,
	0x64, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x32, 0x3f, 0x0a, 0x03, 0x53, 0x50, 0x43, 0x12, 0x38,
	0x0a, 0x09, 0x49, 0x73, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x12, 0x14, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spc_spc_proto_rawDescOnce sync.Once
	file_spc_spc_proto_rawDescData = file_spc_spc_proto_rawDesc
)

func file_spc_spc_proto_rawDescGZIP() []byte {
	file_spc_spc_proto_rawDescOnce.Do(func() {
		file_spc_spc_proto_rawDescData = protoimpl.X.CompressGZIP(file_spc_spc_proto_rawDescData)
	})
	return file_spc_spc_proto_rawDescData
}

var file_spc_spc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spc_spc_proto_goTypes = []interface{}{
	(*HolidayRequest)(nil),  // 0: main.HolidayRequest
	(*HolidayResponse)(nil), // 1: main.HolidayResponse
}
var file_spc_spc_proto_depIdxs = []int32{
	0, // 0: main.SPC.IsHoliday:input_type -> main.HolidayRequest
	1, // 1: main.SPC.IsHoliday:output_type -> main.HolidayResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spc_spc_proto_init() }
func file_spc_spc_proto_init() {
	if File_spc_spc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spc_spc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HolidayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spc_spc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HolidayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spc_spc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spc_spc_proto_goTypes,
		DependencyIndexes: file_spc_spc_proto_depIdxs,
		MessageInfos:      file_spc_spc_proto_msgTypes,
	}.Build()
	File_spc_spc_proto = out.File
	file_spc_spc_proto_rawDesc = nil
	file_spc_spc_proto_goTypes = nil
	file_spc_spc_proto_depIdxs = nil
}
